"""payment expires_at

Revision ID: b78b8ee29ad1
Revises: 8ae33a9af6e8
Create Date: 2026-09-04 19:23:16.723776

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b78b8ee29ad1"
down_revision: str | None = "8ae33a9af6e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "expires_at")
    # ### end Alembic commands ###
