"""add device pin

Revision ID: f2954886a163
Revises: 595f99804502
Create Date: 2026-09-04 17:05:30.499097

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f2954886a163'
down_revision: str | None = '595f99804502'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('pin', sa.String(length=8), server_default='0000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'pin')
    # ### end Alembic commands ###
